
# START OF CODE BLOCK 98c00ad2

# Summary:
# Market risk is the risk that changes in market conditions may adversely impact the value of assets or liabilities, or otherwise negatively impact earnings. This risk is inherent in the financial instruments associated with our operations, primarily within our Global Markets segment. We are also exposed to these risks in other areas of the Corporation (e.g., our ALM activities). In the event of market stress, these risks could have a material impact on our results. For more information, see Interest Rate Risk Management for the Banking Book on page 74.
# Our traditional banking loan and deposit products are non-trading positions and are generally reported at amortized cost for assets or the amount owed for liabilities (historical cost). However, these positions are still subject to changes in economic value based on varying market conditions, with one of the primary risks being changes in the levels of interest rates. The risk of adverse changes in the economic value of our non-trading positions arising from changes in interest rates is managed through our ALM activities. We have elected to account for certain assets and liabilities under the fair value option.
# Our trading positions are reported at fair value with changes reflected in income. Trading positions are subject to various changes in market-based risk factors. The majority of this risk is generated by our activities in the interest rate, foreign exchange, credit, equity and commodities markets. In addition, the values of assets and liabilities could change due to market liquidity, correlations across markets and expectations of market volatility. We seek to manage these risk exposures by using a variety of techniques that encompass a broad range of financial instruments. The key risk management techniques are discussed in more detail in the Trading Risk Management section.
# Global Risk Management is responsible for providing senior management with a clear and comprehensive understanding of the trading risks to which we are exposed. These responsibilities include ownership of market risk policy, developing and maintaining quantitative risk models, calculating aggregated risk measures, establishing and monitoring position limits consistent with risk appetite, conducting daily reviews and analysis of trading inventory, approving material risk exposures and fulfilling regulatory requirements. Market risks that impact businesses outside of Global Markets are monitored and governed by their respective governance functions.
# Quantitative risk models, such as VaR, are an essential component in evaluating the market risks within a portfolio. The Enterprise Model Risk Committee (EMRC), a subcommittee of the MRC, is responsible for providing management oversight and approval of model risk management and governance. The EMRC defines model risk standards, consistent with our risk framework and risk appetite, prevailing regulatory guidance and industry best practice. Models must meet certain validation criteria, including effective challenge of the model development process and a sufficient demonstration of developmental evidence incorporating a comparison of alternative theories and approaches. The EMRC oversees that model standards are consistent with model risk requirements and monitors the effective challenge in the model validation process across the Corporation. In addition, the relevant stakeholders must agree on any required actions or restrictions to the models and maintain a stringent monitoring process for continued compliance.

# Variables:
# var_interest_rate_risk_98c00ad2: Represents exposures to instruments whose values vary with the level or volatility of interest rates.
# var_foreign_exchange_risk_98c00ad2: Represents exposures to changes in the values of current holdings and future cash flows denominated in currencies other than the U.S. dollar.
# var_mortgage_risk_98c00ad2: Represents exposures to changes in the values of mortgage-related instruments.
# var_equity_market_risk_98c00ad2: Represents exposures to securities that represent an ownership interest in a corporation in the form of domestic and foreign common stock or other equity-linked instruments.
# var_commodity_risk_98c00ad2: Represents exposures to instruments traded in the petroleum, natural gas, power and metals markets.
# var_issuer_credit_risk_98c00ad2: Represents exposures to changes in the creditworthiness of individual issuers or groups of issuers.

var_interest_rate_risk_98c00ad2 = None  # TODO: Assign the value for interest rate risk
var_foreign_exchange_risk_98c00ad2 = None  # TODO: Assign the value for foreign exchange risk
var_mortgage_risk_98c00ad2 = None  # TODO: Assign the value for mortgage risk
var_equity_market_risk_98c00ad2 = None  # TODO: Assign the value for equity market risk
var_commodity_risk_98c00ad2 = None  # TODO: Assign the value for commodity risk
var_issuer_credit_risk_98c00ad2 = None  # TODO: Assign the value for issuer credit risk

# END OF CODE BLOCK 98c00ad2
